# Use the latest stable PostgreSQL image
FROM postgres:16

# Set default environment variables for the database
ENV POSTGRES_DB=keycloak
ENV POSTGRES_USER=keycloak
ENV POSTGRES_PASSWORD=keycloak_password

# Expose the default PostgreSQL port
EXPOSE 5432
