# Use the latest stable PostgreSQL image
FROM postgres:16

# Set default database and user (non-sensitive)
ENV POSTGRES_DB=keycloak
ENV POSTGRES_USER=keycloak

# Expose the default PostgreSQL port
EXPOSE 5432
